services:
  # prometheus:
  #   image: prom/prometheus:v3.1.0
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - '9090:9090'
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    # depends_on:
    #   - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
